// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entry_logs.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEntryLog = `-- name: CreateEntryLog :one
INSERT INTO entry_logs (pass_id, guard_user_id, action, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, pass_id, guard_user_id, action, action_at, comment
`

type CreateEntryLogParams struct {
	PassID      uuid.UUID      `json:"pass_id"`
	GuardUserID uuid.UUID      `json:"guard_user_id"`
	Action      string         `json:"action"`
	Comment     sql.NullString `json:"comment"`
}

func (q *Queries) CreateEntryLog(ctx context.Context, arg CreateEntryLogParams) (EntryLog, error) {
	row := q.db.QueryRowContext(ctx, createEntryLog,
		arg.PassID,
		arg.GuardUserID,
		arg.Action,
		arg.Comment,
	)
	var i EntryLog
	err := row.Scan(
		&i.ID,
		&i.PassID,
		&i.GuardUserID,
		&i.Action,
		&i.ActionAt,
		&i.Comment,
	)
	return i, err
}

const listEntryLogsByPass = `-- name: ListEntryLogsByPass :many
SELECT id, pass_id, guard_user_id, action, action_at, comment FROM entry_logs
WHERE pass_id = $1
ORDER BY action_at DESC
LIMIT $2 OFFSET $3
`

type ListEntryLogsByPassParams struct {
	PassID uuid.UUID `json:"pass_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListEntryLogsByPass(ctx context.Context, arg ListEntryLogsByPassParams) ([]EntryLog, error) {
	rows, err := q.db.QueryContext(ctx, listEntryLogsByPass, arg.PassID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryLog
	for rows.Next() {
		var i EntryLog
		if err := rows.Scan(
			&i.ID,
			&i.PassID,
			&i.GuardUserID,
			&i.Action,
			&i.ActionAt,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
