// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: guest_requests.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGuestRequest = `-- name: CreateGuestRequest :one
INSERT INTO guest_requests (resident_user_id, guest_full_name, plate_number, valid_from, valid_to, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, resident_user_id, guest_full_name, plate_number, valid_from, valid_to, status, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateGuestRequestParams struct {
	ResidentUserID uuid.UUID     `json:"resident_user_id"`
	GuestFullName  string        `json:"guest_full_name"`
	PlateNumber    string        `json:"plate_number"`
	ValidFrom      time.Time     `json:"valid_from"`
	ValidTo        time.Time     `json:"valid_to"`
	Status         string        `json:"status"`
	CreatedBy      uuid.NullUUID `json:"created_by"`
	UpdatedBy      uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) CreateGuestRequest(ctx context.Context, arg CreateGuestRequestParams) (GuestRequest, error) {
	row := q.db.QueryRowContext(ctx, createGuestRequest,
		arg.ResidentUserID,
		arg.GuestFullName,
		arg.PlateNumber,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i GuestRequest
	err := row.Scan(
		&i.ID,
		&i.ResidentUserID,
		&i.GuestFullName,
		&i.PlateNumber,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getGuestRequestByID = `-- name: GetGuestRequestByID :one
SELECT id, resident_user_id, guest_full_name, plate_number, valid_from, valid_to, status, created_at, updated_at, created_by, updated_by, deleted_at FROM guest_requests WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGuestRequestByID(ctx context.Context, id uuid.UUID) (GuestRequest, error) {
	row := q.db.QueryRowContext(ctx, getGuestRequestByID, id)
	var i GuestRequest
	err := row.Scan(
		&i.ID,
		&i.ResidentUserID,
		&i.GuestFullName,
		&i.PlateNumber,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getGuestRequestByIDAny = `-- name: GetGuestRequestByIDAny :one
SELECT id, resident_user_id, guest_full_name, plate_number, valid_from, valid_to, status, created_at, updated_at, created_by, updated_by, deleted_at FROM guest_requests WHERE id = $1
`

func (q *Queries) GetGuestRequestByIDAny(ctx context.Context, id uuid.UUID) (GuestRequest, error) {
	row := q.db.QueryRowContext(ctx, getGuestRequestByIDAny, id)
	var i GuestRequest
	err := row.Scan(
		&i.ID,
		&i.ResidentUserID,
		&i.GuestFullName,
		&i.PlateNumber,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listGuestRequests = `-- name: ListGuestRequests :many
SELECT id, resident_user_id, guest_full_name, plate_number, valid_from, valid_to, status, created_at, updated_at, created_by, updated_by, deleted_at FROM guest_requests
WHERE ($1::bool) OR deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListGuestRequestsParams struct {
	Column1 bool  `json:"column_1"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListGuestRequests(ctx context.Context, arg ListGuestRequestsParams) ([]GuestRequest, error) {
	rows, err := q.db.QueryContext(ctx, listGuestRequests, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuestRequest
	for rows.Next() {
		var i GuestRequest
		if err := rows.Scan(
			&i.ID,
			&i.ResidentUserID,
			&i.GuestFullName,
			&i.PlateNumber,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestRequestsByResident = `-- name: ListGuestRequestsByResident :many
SELECT id, resident_user_id, guest_full_name, plate_number, valid_from, valid_to, status, created_at, updated_at, created_by, updated_by, deleted_at FROM guest_requests
WHERE resident_user_id = $1 AND (($2::bool) OR deleted_at IS NULL)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListGuestRequestsByResidentParams struct {
	ResidentUserID uuid.UUID `json:"resident_user_id"`
	Column2        bool      `json:"column_2"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListGuestRequestsByResident(ctx context.Context, arg ListGuestRequestsByResidentParams) ([]GuestRequest, error) {
	rows, err := q.db.QueryContext(ctx, listGuestRequestsByResident,
		arg.ResidentUserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuestRequest
	for rows.Next() {
		var i GuestRequest
		if err := rows.Scan(
			&i.ID,
			&i.ResidentUserID,
			&i.GuestFullName,
			&i.PlateNumber,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreGuestRequest = `-- name: RestoreGuestRequest :exec
UPDATE guest_requests
SET deleted_at = NULL,
    updated_at = now(),
    updated_by = $2
WHERE id = $1
`

type RestoreGuestRequestParams struct {
	ID        uuid.UUID     `json:"id"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) RestoreGuestRequest(ctx context.Context, arg RestoreGuestRequestParams) error {
	_, err := q.db.ExecContext(ctx, restoreGuestRequest, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteGuestRequest = `-- name: SoftDeleteGuestRequest :exec
UPDATE guest_requests
SET deleted_at = now(),
    updated_at = now(),
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteGuestRequestParams struct {
	ID        uuid.UUID     `json:"id"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteGuestRequest(ctx context.Context, arg SoftDeleteGuestRequestParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteGuestRequest, arg.ID, arg.UpdatedBy)
	return err
}

const updateGuestRequest = `-- name: UpdateGuestRequest :one
UPDATE guest_requests
SET guest_full_name = $2,
    plate_number = $3,
    valid_from = $4,
    valid_to = $5,
    status = $6,
    updated_at = now(),
    updated_by = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, resident_user_id, guest_full_name, plate_number, valid_from, valid_to, status, created_at, updated_at, created_by, updated_by, deleted_at
`

type UpdateGuestRequestParams struct {
	ID            uuid.UUID     `json:"id"`
	GuestFullName string        `json:"guest_full_name"`
	PlateNumber   string        `json:"plate_number"`
	ValidFrom     time.Time     `json:"valid_from"`
	ValidTo       time.Time     `json:"valid_to"`
	Status        string        `json:"status"`
	UpdatedBy     uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) UpdateGuestRequest(ctx context.Context, arg UpdateGuestRequestParams) (GuestRequest, error) {
	row := q.db.QueryRowContext(ctx, updateGuestRequest,
		arg.ID,
		arg.GuestFullName,
		arg.PlateNumber,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Status,
		arg.UpdatedBy,
	)
	var i GuestRequest
	err := row.Scan(
		&i.ID,
		&i.ResidentUserID,
		&i.GuestFullName,
		&i.PlateNumber,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
