// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, full_name, plot_number, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, password_hash, role, full_name, plot_number, blocked_at, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Role         string         `json:"role"`
	FullName     string         `json:"full_name"`
	PlotNumber   sql.NullString `json:"plot_number"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	UpdatedBy    uuid.NullUUID  `json:"updated_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.FullName,
		arg.PlotNumber,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.PlotNumber,
		&i.BlockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, full_name, plot_number, blocked_at, created_at, updated_at, created_by, updated_by, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.PlotNumber,
		&i.BlockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, full_name, plot_number, blocked_at, created_at, updated_at, created_by, updated_by, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.PlotNumber,
		&i.BlockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDAny = `-- name: GetUserByIDAny :one
SELECT id, email, password_hash, role, full_name, plot_number, blocked_at, created_at, updated_at, created_by, updated_by, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByIDAny(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDAny, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.PlotNumber,
		&i.BlockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, full_name, plot_number, blocked_at, created_at, updated_at, created_by, updated_by, deleted_at FROM users
WHERE ($1::bool) OR deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	Column1 bool  `json:"column_1"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.FullName,
			&i.PlotNumber,
			&i.BlockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at = NULL,
    updated_at = now(),
    updated_by = $2
WHERE id = $1
`

type RestoreUserParams struct {
	ID        uuid.UUID     `json:"id"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) RestoreUser(ctx context.Context, arg RestoreUserParams) error {
	_, err := q.db.ExecContext(ctx, restoreUser, arg.ID, arg.UpdatedBy)
	return err
}

const blockUser = `-- name: BlockUser :exec
UPDATE users
SET blocked_at = now(),
    updated_at = now(),
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type BlockUserParams struct {
	ID        uuid.UUID     `json:"id"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.ExecContext(ctx, blockUser, arg.ID, arg.UpdatedBy)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now(),
    updated_at = now(),
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	ID        uuid.UUID     `json:"id"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, arg.ID, arg.UpdatedBy)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2,
    role = $3,
    full_name = $4,
    plot_number = $5,
    updated_at = now(),
    updated_by = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, role, full_name, plot_number, blocked_at, created_at, updated_at, created_by, updated_by, deleted_at
`

type UpdateUserParams struct {
	ID         uuid.UUID      `json:"id"`
	Email      string         `json:"email"`
	Role       string         `json:"role"`
	FullName   string         `json:"full_name"`
	PlotNumber sql.NullString `json:"plot_number"`
	UpdatedBy  uuid.NullUUID  `json:"updated_by"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.FullName,
		arg.PlotNumber,
		arg.UpdatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.PlotNumber,
		&i.BlockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2,
    updated_at = now(),
    updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, role, full_name, plot_number, blocked_at, created_at, updated_at, created_by, updated_by, deleted_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID     `json:"id"`
	PasswordHash string        `json:"password_hash"`
	UpdatedBy    uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedBy)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.PlotNumber,
		&i.BlockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const unblockUser = `-- name: UnblockUser :exec
UPDATE users
SET blocked_at = NULL,
    updated_at = now(),
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UnblockUserParams struct {
	ID        uuid.UUID     `json:"id"`
	UpdatedBy uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.ExecContext(ctx, unblockUser, arg.ID, arg.UpdatedBy)
	return err
}
